name: Kong Stack 

on:
 workflow_dispatch:

jobs:
  Kong_stack:
    uses: veecode-platform/vkpr_templates/.github/workflows/Kong_Stack.yml@1.3.5
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      KONG_ADMIN_PASSWORD: ${{ secrets.KONG_ADMIN_PASSWORD }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      KONG_LICENSE: ${{ secrets.KONG_LICENSE }}

